language: node_js
node_js: node
install:
- npm install
script:
- npm run travis
deploy:
  provider: npm
  email: zouxuoz@gmail.com
  skip_cleanup: true
  api_key:
    secure: "YV+MEyr2m7lW/kdkQFCqAt2mnarIWizyWBElVxPYjm+bM89VK+Tc2goI1hlqSbFzEyATzZeZHCfyQIFdf3CTRH/IxcvCY9zhntMYE9cD2LmrQgyXjgCXy0YOAeK8qQGVqlQEMM0MQrhjhFG/AZ2fulWhLTbXi1yj7D9kkJtioxUHIGhztO8Ca6YNjRPJbzGUsp3LvYbIeP061ruQ6g/BJFmMdWPGgwZ0uaVNEgsv9ZyzxuRoqTZ3b3UvoxA1Ejrg/17kfggtymLiodbYrNkZikLWshgNZN+m37PgrPIgFIFMc0Hqy1pgH9CEYuL3Jnb74DZqtgRVfXRqex/souwnzRsRdZi6TiUMK9GadQDfbiRIgaKm28K1LXSO9BqUEGdrOFTaV8Q2XeIX0ifvRJ+LS+3ZC7VWrAStwbqbj4/jMJqAutgqILdQVfuAKnR9djRgk5zlvy7R9h8e3G5sdiMEPLPsQcHFa8nNLGivYCR/Iif/ieJILREsWfOOnm26VN16wZynBZuaqhpLQEFyB+3XtUcCwimTCiHEvInP/IxzR6mMExDTk1yT3H529ZBHKPlOQLo2in+Y/wX7sXcjQKOVAlZm2+YZ1PFs6SqRomSCqQoXsqr7AWC4f3EGNwUhSyN2mUGTusTfRpfDdvk5tuqOQM71vvZgAoA5h1u3VpWKyzA="
  on:
    tags: true
    repo: 8base/dev-api-cli
    branch: master
